# Generated by Django 3.0.4 on 2020-04-06 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_de_tipo_de_item', '0007_auto_20200401_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=40)),
                ('tipo_de_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_tipo_de_item.TipoDeItem')),
            ],
        ),
        migrations.CreateModel(
            name='VersionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=400)),
                ('version', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('antecesores', models.ManyToManyField(related_name='antecesores', to='gestion_de_item.Item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_item', to='gestion_de_item.Item')),
                ('padres', models.ManyToManyField(related_name='padres', to='gestion_de_item.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_version', to='gestion_de_item.VersionItem'),
        ),
        migrations.CreateModel(
            name='AtributoItemNumerico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=20, max_digits=20)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_tipo_de_item.AtributoNumerico')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_item.VersionItem')),
            ],
        ),
        migrations.CreateModel(
            name='AtributoItemFecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DateTimeField()),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_tipo_de_item.AtributoFecha')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_item.VersionItem')),
            ],
        ),
        migrations.CreateModel(
            name='AtributoItemCadena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=500)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_tipo_de_item.AtributoCadena')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_item.VersionItem')),
            ],
        ),
        migrations.CreateModel(
            name='AtributoItemBooleano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.BooleanField()),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_tipo_de_item.AtributoBooleano')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_item.VersionItem')),
            ],
        ),
        migrations.CreateModel(
            name='AtributoItemArchivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_tipo_de_item.AtributoBinario')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_item.VersionItem')),
            ],
        ),
    ]
