# Generated by Django 3.0.4 on 2020-04-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_item', '0002_auto_20200406_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributoitemnumerico',
            name='valor',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
    ]
