# Generated by Django 3.0.4 on 2020-04-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_item', '0003_auto_20200410_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atributoitemarchivo',
            old_name='url',
            new_name='valor',
        ),
    ]
