# Generated by Django 3.0.5 on 2020-04-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_item', '0004_auto_20200410_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributoitemarchivo',
            name='valor',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='atributoitembooleano',
            name='valor',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='atributoitemcadena',
            name='valor',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='atributoitemfecha',
            name='valor',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='atributoitemnumerico',
            name='valor',
            field=models.DecimalField(decimal_places=20, max_digits=40, null=True),
        ),
    ]
