# Generated by Django 3.0.4 on 2020-04-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_item', '0006_auto_20200414_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionitem',
            name='antecesores',
        ),
        migrations.RemoveField(
            model_name='versionitem',
            name='padres',
        ),
        migrations.AddField(
            model_name='item',
            name='antecesores',
            field=models.ManyToManyField(related_name='_item_antecesores_+', to='gestion_de_item.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='padres',
            field=models.ManyToManyField(related_name='_item_padres_+', to='gestion_de_item.Item'),
        ),
    ]
