# Generated by Django 3.0.4 on 2020-04-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_item', '0007_auto_20200414_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='antecesores',
            field=models.ManyToManyField(related_name='antecesores_item', to='gestion_de_item.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='padres',
            field=models.ManyToManyField(related_name='padres_item', to='gestion_de_item.Item'),
        ),
    ]
