# Generated by Django 3.0.5 on 2020-04-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_item', '0008_auto_20200414_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='antecesores',
        ),
        migrations.RemoveField(
            model_name='item',
            name='padres',
        ),
        migrations.AddField(
            model_name='versionitem',
            name='antecesores',
            field=models.ManyToManyField(related_name='sucesores', to='gestion_de_item.Item'),
        ),
        migrations.AddField(
            model_name='versionitem',
            name='padres',
            field=models.ManyToManyField(related_name='hijos', to='gestion_de_item.Item'),
        ),
    ]
