# Generated by Django 3.0.5 on 2020-04-28 00:04

import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gestion_de_item', '0009_auto_20200427_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributoitemarchivo',
            name='archivo_temporal',
            field=models.FileField(null=True, upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='atributoitemarchivo',
            name='valor',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='items/'),
        ),
    ]
