# Generated by Django 3.0.6 on 2020-08-24 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_proyecto', '0020_auto_20200401_1759'),
        ('gestion_de_item', '0010_auto_20200427_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='encargado_de_modificar',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_de_proyecto.Participante'),
        ),
        migrations.AddField(
            model_name='item',
            name='estado_anterior',
            field=models.CharField(default='', max_length=40),
        ),
    ]
