# Generated by Django 3.0.5 on 2020-09-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_item', '0012_auto_20200903_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cambio_necesario',
            field=models.CharField(default='', max_length=500),
        ),
    ]
