# Generated by Django 3.0.5 on 2020-09-22 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_item', '0013_item_cambio_necesario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionitem',
            name='peso',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'El peso de un item debe ser mayor a 0')]),
        ),
    ]
