# Generated by Django 3.0.4 on 2020-03-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('faseCerrada', models.BooleanField(verbose_name='Fase Cerrada')),
                ('puedeCerrarse', models.BooleanField(verbose_name='Puede Cerrarse')),
            ],
        ),
    ]
