# Generated by Django 3.0.4 on 2020-03-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_fase', '0002_fase_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
