# Generated by Django 3.0.4 on 2020-03-31 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_fase', '0006_auto_20200324_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fase',
            options={'permissions': [('g_pp_crear_fase', 'Crear Fase dentro de Proyecto'), ('g_pp_editar_fase', 'Editar Fase dentro de Proyecto'), ('g_pp_f_eliminar_fase', 'Eliminar Fase de Proyecto'), ('pp_f_ver_fase', 'Visualizar Fase dentro de Proyecto'), ('pp_f_cerrar_fase', 'Cerrar Fase de Proyecto')]},
        ),
    ]
