# Generated by Django 3.0.4 on 2020-04-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_fase', '0007_auto_20200331_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fase',
            options={},
        ),
    ]
