# Generated by Django 3.0.5 on 2020-08-23 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_solicitud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicituddecambio',
            name='votos_a_favor',
        ),
        migrations.RemoveField(
            model_name='solicituddecambio',
            name='votos_en_contra',
        ),
    ]
