# Generated by Django 3.0.6 on 2020-08-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_solicitud', '0002_auto_20200823_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddecambio',
            name='estado',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
