# Generated by Django 3.0.6 on 2020-08-23 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_solicitud', '0003_solicituddecambio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddecambio',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
