# Generated by Django 3.0.5 on 2020-08-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_solicitud', '0005_auto_20200823_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='motivo',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
    ]
