# Generated by Django 3.0.4 on 2020-03-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolDeSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('permisos', models.ManyToManyField(to='auth.Permission')),
            ],
            options={
                'permissions': [('ps_crear_rs', 'Crear nuevo Rol de Sistema'), ('ps_ver_rs', 'Visualizar Lista de Roles de Sistema'), ('ps_eliminar_rs', 'Eliminar Rol de Sistema'), ('ps_asignar_rs', 'Asignar Roles de Sistema ')],
            },
        ),
    ]
