# Generated by Django 3.0.5 on 2020-04-30 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_de_sistema', '0004_auto_20200413_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roldesistema',
            options={'permissions': [('pa_crear_proyecto', 'Crear Proyecto'), ('pa_cancelar_proyecto', 'Cancelar Proyecto'), ('ps_ver_proyecto', 'Visualizar lista de todos los Proyectos guardados en el Sistema'), ('ps_ver_rs', 'Visualizar Lista de Roles de Sistema'), ('pa_crear_rs', 'Crear nuevo Rol de Sistema'), ('pa_eliminar_rs', 'Eliminar Rol de Sistema'), ('pa_asignar_rs', 'Asignar Rol de Sistema'), ('pa_desasignar_rs', 'Desasignar Rol de Sistema'), ('pa_editar_rs', 'Editar Rol de Sistema'), ('pa_crear_rp', 'Crear Rol de Proyecto'), ('ps_ver_rp', 'Visualizar Lista de Roles de Proyecto'), ('pa_eliminar_rp', 'Eliminar Rol de Proyecto'), ('pa_editar_rp', 'Editar Rol de Proyecto'), ('ps_ver_usuarios', 'Visualizar lista de todos los Usuarios registrados en el Sistema'), ('pa_desactivar_usuario', 'Desactiva a un Usuario del Sistema'), ('pa_config_cloud', 'Configurar Conexión con el servicio de almacenamiento en la nube'), ('pa_config_sso', 'Configurar Conexión con SSO'), ('pu_acceder_sistema', 'Acceder al Sistema')]},
        ),
    ]
