# Generated by Django 3.0.5 on 2020-08-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_de_item', '0010_auto_20200427_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=40)),
                ('items', models.ManyToManyField(to='gestion_de_item.Item')),
            ],
        ),
    ]
