# Generated by Django 3.0.5 on 2020-08-23 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_fase', '0008_auto_20200401_1753'),
        ('gestion_linea_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineabase',
            name='fase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_de_fase.Fase'),
        ),
    ]
