# Generated by Django 3.0.5 on 2020-09-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_notificaciones', '0002_auto_20200922_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
