# Generated by Django 3.0.4 on 2020-03-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('roles_de_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roldeproyecto',
            name='permisos',
        ),
        migrations.AddField(
            model_name='roldeproyecto',
            name='permisos',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
    ]
