# Generated by Django 3.0.4 on 2020-03-23 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_de_proyecto', '0006_permisosporfase'),
        ('roles_de_proyecto', '0005_auto_20200319_2303'),
    ]

    operations = [
    ]
