# Generated by Django 3.0.4 on 2020-04-01 00:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('roles_de_proyecto', '0007_merge_20200323_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roldeproyecto',
            options={},
        ),
    ]
