# Generated by Django 3.0.4 on 2020-04-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_de_proyecto', '0008_auto_20200401_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roldeproyecto',
            options={'permissions': [('pg_iniciar_proyecto', 'Iniciar Proyecto'), ('pg_cancelar_proyecto', 'Cancelar Proyecto'), ('pu_ver_proyecto', 'Visualizar Proyecto'), ('pg_crear_fase', 'Crear Fase dentro de Proyecto'), ('pg_editar_fase', 'Editar Fase dentro de Proyecto'), ('pg_f_eliminar_fase', 'Eliminar Fase de Proyecto'), ('pp_f_ver_fase', 'Visualizar Fase dentro de Proyecto'), ('pp_f_cerrar_fase', 'Cerrar Fase de Proyecto'), ('pp_f_crear_tipo_de_item', 'Crear tipo de ítem'), ('pp_f_eliminar_tipo_de_item', 'Eliminar tipo de ítem'), ('pp_f_editar_tipo_de_item', 'Editar tipo de ítem'), ('pp_f_importar_tipo_de_item', 'Importar tipo de ítem')]},
        ),
    ]
