# Generated by Django 3.0.4 on 2020-03-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_proyecto', '0002_auto_20200321_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(max_length=400),
        ),
    ]
