# Generated by Django 3.0.4 on 2020-03-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_proyecto', '0003_auto_20200321_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participante',
            options={'permissions': [('pp_agregar_participante', 'Agregar Participante al Proyecto'), ('pp_eliminar_participante', 'Eliminar Participante del Proyecto'), ('pp_asignar_rp_a_participante', 'Asignar Rol de Proyecto a Participante'), ('pp_desasignar_rp_a_participante', 'Desasignar Rol de Proyecto a Participante')]},
        ),
    ]
