# Generated by Django 3.0.4 on 2020-03-24 14:14

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_de_proyecto', '0006_auto_20200324_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': [('ps_crear_pry', 'Crear Proyecto'), ('ps_cancelar_pry', 'Cancelar Proyecto'), ('ps_ver_pry', 'Visualizar lista de todos los Proyectos guardados en el Sistema')]},
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_de_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='gerente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
    ]
