# Generated by Django 3.0.4 on 2020-03-24 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_proyecto', '0007_auto_20200324_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_de_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creacion'),
        ),
    ]
