# Generated by Django 3.0.4 on 2020-03-24 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_proyecto', '0007_auto_20200324_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_de_creacion',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 14, 15, 39, 420288, tzinfo=utc), verbose_name='Fecha de Creacion'),
        ),
    ]
