# Generated by Django 3.0.4 on 2020-03-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_proyecto', '0010_auto_20200324_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': [('ps_crear_proyecto', 'Crear Proyecto'), ('ps_cancelar_proyecto', 'Cancelar Proyecto'), ('ps_ver_proyecto', 'Visualizar lista de todos los Proyectos guardados en el Sistema'), ('g_pp_iniciar_proyecto', 'Iniciar Proyecto')]},
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
