# Generated by Django 3.0.4 on 2020-03-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_proyecto', '0013_auto_20200331_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
