# Generated by Django 3.0.4 on 2020-03-31 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_proyecto', '0015_auto_20200331_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participante',
            options={'permissions': [('pp_ver_participante', 'Visualizar Participantes del Proyecto'), ('pp_agregar_participante', 'Agregar Participante al Proyecto'), ('pp_eliminar_participante', 'Eliminar Participante del Proyecto'), ('pp_asignar_rp_a_participante', 'Asignar Rol de Proyecto a Participante')]},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': [('ps_crear_proyecto', 'Crear Proyecto'), ('ps_cancelar_proyecto', 'Cancelar Proyecto'), ('ps_ver_proyecto', 'Visualizar lista de todos los Proyectos guardados en el Sistema'), ('g_pp_iniciar_proyecto', 'Iniciar Proyecto'), ('g_pp_cancelar_proyecto', 'Cancelar Proyecto'), ('pp_ver_proyecto', 'Visualizar Proyecto')]},
        ),
    ]
