# Generated by Django 3.0.4 on 2020-03-31 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_proyecto', '0016_comite'),
        ('gestion_de_proyecto', '0016_auto_20200331_1800'),
    ]

    operations = [
    ]
