# Generated by Django 3.0.4 on 2020-04-01 00:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gestion_de_proyecto', '0017_merge_20200331_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': [('g_pp_iniciar_proyecto', 'Iniciar Proyecto'),
                                     ('g_pp_cancelar_proyecto', 'Cancelar Proyecto'),
                                     ('pp_ver_proyecto', 'Visualizar Proyecto')]},
        ),
    ]
