# Generated by Django 3.0.4 on 2020-04-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_proyecto', '0018_auto_20200401_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={},
        ),
    ]
