# Generated by Django 3.0.4 on 2020-04-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_proyecto', '0019_auto_20200401_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participante',
            options={},
        ),
    ]
