# Generated by Django 3.0.4 on 2020-03-21 14:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_de_fase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=400)),
                ('fecha_creacion', models.DateTimeField()),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_fase.Fase')),
            ],
        ),
        migrations.CreateModel(
            name='AtributoNumerico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('requerido', models.BooleanField()),
                ('max_digitos', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'La maxima cantidad de digitos debe ser un numero mayor o igual a 0'), django.core.validators.MaxValueValidator(20, 'El maximo numero de digitos permitidos es 20')])),
                ('max_decimales', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'La maxima cantidad de digitos decimales debe ser un numero mayor o igual a 0'), django.core.validators.MaxValueValidator(20, 'El maximo numero de digitos decimales permitidos es 20')])),
                ('tipo_de_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_tipo_de_item.TipoDeItem')),
            ],
        ),
        migrations.CreateModel(
            name='AtributoFecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('requerido', models.BooleanField()),
                ('tipo_de_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_tipo_de_item.TipoDeItem')),
            ],
        ),
        migrations.CreateModel(
            name='AtributoCadena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('requerido', models.BooleanField()),
                ('max_longitud', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'La longitud maxima de la cadena debe ser un numero mayor o igual a 0'), django.core.validators.MaxValueValidator(500, 'La longlitud maxima de la cadena es 500')])),
                ('tipo_de_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_tipo_de_item.TipoDeItem')),
            ],
        ),
        migrations.CreateModel(
            name='AtributoBooleano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('requerido', models.BooleanField()),
                ('tipo_de_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_tipo_de_item.TipoDeItem')),
            ],
        ),
        migrations.CreateModel(
            name='AtributoBinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('requerido', models.BooleanField()),
                ('max_tamaño', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'El tamaño maximo para el archivo debe ser mayor o igual a 1')])),
                ('tipo_de_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_tipo_de_item.TipoDeItem')),
            ],
        ),
    ]
