# Generated by Django 3.0.4 on 2020-03-30 00:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_tipo_de_item', '0003_auto_20200323_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributobinario',
            name='max_tamaño',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'El tamaño maximo para el archivo debe ser mayor o igual a 1MB')], verbose_name='Tamaño Máximo (MB)'),
        ),
        migrations.AlterField(
            model_name='atributocadena',
            name='max_longitud',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'La longitud maxima de la cadena debe ser un numero mayor o igual a 0'), django.core.validators.MaxValueValidator(500, 'La longlitud maxima de la cadena es 500')], verbose_name='Longitud Maxima'),
        ),
        migrations.AlterField(
            model_name='atributonumerico',
            name='max_decimales',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'La máxima cantidad de digitos decimales debe ser un numero mayor o igual a 0'), django.core.validators.MaxValueValidator(20, 'El máximo numero de digitos decimales permitidos es 20')], verbose_name='Maxima cantidad de posiciones decimales'),
        ),
        migrations.AlterField(
            model_name='atributonumerico',
            name='max_digitos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'La máxima cantidad de digitos debe ser un numero mayor o igual a 0'), django.core.validators.MaxValueValidator(20, 'El máximo numero de digitos permitidos es 20')], verbose_name='Maxima cantidad de digitos'),
        ),
    ]
