# Generated by Django 3.0.4 on 2020-03-30 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_tipo_de_item', '0004_auto_20200330_0023'),
        ('gestion_de_tipo_de_item', '0004_auto_20200327_1342'),
    ]

    operations = [
    ]
