# Generated by Django 3.0.5 on 2020-04-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_tipo_de_item', '0007_auto_20200401_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributobooleano',
            name='requerido',
            field=models.BooleanField(default=False),
        ),
    ]
